### ISSUE TITLE
Organisation of code

### ISSUE THREAD

**Issue by BenjaminMatembe** [romans-adi/todo-app#8]
Hi @romans-adi and @gersonhiggins , well done on the project. It looks really good and it is working well and also it is well tested using JEST library. 

I have however noticed that your **src folder** has **svgs and png icons** scattered with in, I think it would be better to create for them a folder from which you will import them from just like you did for the icons in the **favicon folder.**

**Your src folder looks like this**
<img width="226" alt="image" src="https://github.com/romans-adi/todo-app/assets/88074420/72a4e4ab-1045-4738-8dd2-eaffdd98fb65">

This way you will have made your code base more organised.

Happy coding!

**Comment by romans-adi** [comment]
Thank you for this suggestion!
All the icons moved to the new directory `icons` under the newly created `img` directory.  :rocket: :robot: :rock:
